services:
    postgres:
        image: postgres:16.2-alpine3.19
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: petstore
        volumes:
            - /var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d petstore"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    # spring-app:
    #     build: .
    #     container_name: spring-app
    #     environment:
    #         SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petstore
    #         SPRING_DATASOURCE_USERNAME: postgres
    #         SPRING_DATASOURCE_PASSWORD: password
    #     ports:
    #         - "8000:8000"
    #     depends_on:
    #         postgres:
    #             condition: service_healthy
